image: python:3.9

# set up SNL proxy
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# cache project dependencies
cache:
  paths:
    - .cache/pip
    - venv/

# set up environment, dependencies before jobs
before_script:
  - update-ca-certificates
  - pip install -e .

stages:
  - test

test:
  stage: test
  tags:
    - test
  script:
    - cd tests
    - python -m unittest discover
